image: tgbyte/builder
stages:
  - build-image
  - build-manifest

variables:
  MULTIARCH: 1

.build-image-template: &build-image
  stage: build-image
  script:
    - ./bin/build-image.sh
  artifacts:
    expire_in: 1 day
    paths:
      - results/
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

build-image-amd64:
  <<: *build-image

build-image-arm:
  <<: *build-image
  variables:
    ARCH: arm

build-manifest:
  stage: build-manifest
  script:
    - ./bin/build-manifest.sh
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
