image: tgbyte/builder

stages:
  - build-image
  - build-manifest

variables:
  MULTIARCH: 1

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

.build-image-template: &build-image
  stage: build-image
  script:
    - ./bin/build-image.sh
  artifacts:
    expire_in: 1 day
    paths:
      - results/

build-image-amd64:
  <<: *build-image

build-image-arm64:
  <<: *build-image
  variables:
    ARCH: arm64

build-manifest:
  stage: build-manifest
  needs:
    - job: build-image-amd64
    - job: build-image-arm64
  script:
    - ./bin/build-manifest.sh
