include:
  - project: 'docker/builder'
    file: '/templates/.gitlab-ci.yml'

variables:
  BUILD_IMAGE_SCRIPT: .gitlab-ci/build-image.sh
  MULTIARCH: 1
  TRIVY_SCRIPT: bin/trivy.sh
  TRIVY_SEVERITY: CRITICAL
  SKIP_TRIVY: 1
