cache:
  paths:
    - .trivy/

stages:
  - scan
  - build-image
  - build-manifest

trivy:
  stage: scan
  script:
    - ${TRIVY_SCRIPT:-trivy.sh}
  allow_failure: true
  artifacts:
    expire_in: 1 day
    paths:
      - .trivy
      - .trivy-vulnerable
    when: always
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $CI_PIPELINE_SOURCE != "push"

.build-image-template: &build-image
  stage: build-image
  script:
    - ${BUILD_IMAGE_SCRIPT:-build-image.sh}
  artifacts:
    expire_in: 1 day
    paths:
      - results/
  needs:
    - job: trivy
      optional: true
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

build-amd64:
  <<: *build-image

build-arm64:
  <<: *build-image
  rules:
    - if: $MULTIARCH == "1"
  variables:
    ARCH: arm64

build-manifest:
  stage: build-manifest
  script:
    - ${BUILD_MANIFEST_SCRIPT:-build-manifest.sh}
  needs:
    - job: trivy
      optional: true
    - job: build-amd64
    - job: build-arm64
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $MULTIARCH == "1"
