cache:
  paths:
    - .trivy/

stages:
  - scan
  - build
  - verify

trivy:
  stage: scan
  script:
    - ${TRIVY_SCRIPT:-trivy.sh}
  allow_failure: true
  artifacts:
    expire_in: 1 day
    paths:
      - .trivy-run
      - .trivy-vulnerable
      - .version
    when: always
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $CI_PIPELINE_SOURCE != "push"

build:
  stage: build
  script:
    - ${BUILD_IMAGE_SCRIPT:-build-image.sh}
  variables:
    BUILDKITD_FLAGS: --oci-worker-no-process-sandbox
  artifacts:
    expire_in: 1 day
    paths:
      - results/
      - '**/results/'
      - .version
  needs:
    - job: trivy
      optional: true
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

trivy-result:
  stage: verify
  script:
    - ${TRIVY_SCRIPT:-trivy.sh}
  artifacts:
    expire_in: 1 month
    paths:
      - .trivy-report.json
    when: always
  needs:
    - job: trivy
      optional: true
    - job: build
  variables:
    TRIVY_DISABLE_VEX_NOTICE: 1
    TRIVY_REPORT_JSON: 1
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $SKIP_TRIVY != "1"

variables:
  TRIVY_DISABLE_VEX_NOTICE: '1'
